# Generated by Django 5.2.10 on 2026-02-02 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallpapers', '0007_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionWallpaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_wallpapers', to='wallpaper_collections.collection')),
                ('wallpaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_entries', to='wallpapers.wallpaper')),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('collection', 'wallpaper')},
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='wallpapers',
            field=models.ManyToManyField(related_name='collections', through='wallpaper_collections.CollectionWallpaper', to='wallpapers.wallpaper'),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('user', 'title')},
        ),
    ]
