version: '3.8'

services:

  db:
    image: postgres:15
    container_name: wallstash_db
    restart: always
    env_file:
      - ./backend-django/wallstash/.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wallstash_user"]
      interval: 5s
      timeout: 5s
      retries: 5


  rabbitmq:
    image: rabbitmq:3-management
    container_name: wallstash_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq


  backend:
    build: ./backend-django/wallstash
    container_name: wallstash_backend
    restart: always
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend-django/wallstash/:/app
      - static_volume:/app/static
      - ./backend-django/wallstash/media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./backend-django/wallstash/.env
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
  celery:
    build: ./backend-django/wallstash
    container_name: wallstash_celery
    restart: always
    command: celery -A wallstash worker -l info
    volumes:
      - ./backend-django/wallstash/:/app
    env_file:
      - ./backend-django/wallstash/.env
    depends_on:
      - rabbitmq
      - db

volumes:
  postgres_data:
  static_volume:
  media_volume:
  rabbitmq_data: