# Generated by Django 5.2.10 on 2026-01-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='file_size',
            field=models.PositiveBigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='height',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='image',
            field=models.ImageField(upload_to='wallpapers/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='width',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
