# Generated by Django 5.2.10 on 2026-01-30 18:33

import wallpapers.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapers', '0002_alter_wallpaper_file_size_alter_wallpaper_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='image',
            field=models.ImageField(upload_to=wallpapers.utils.wallpaper_upload_to),
        ),
    ]
