# Generated by Django 5.2.10 on 2026-01-30 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapers', '0003_category_alter_wallpaper_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallpapers', to='wallpapers.category'),
        ),
    ]
