# Generated by Django 5.2.10 on 2026-01-30 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapers', '0004_wallpaper_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallpapers', to='wallpapers.category'),
        ),
    ]
