# Generated by Django 5.2.10 on 2026-01-31 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapers', '0005_alter_wallpaper_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallpaper',
            old_name='downloads',
            new_name='downloads_count',
        ),
        migrations.RenameField(
            model_name='wallpaper',
            old_name='likes',
            new_name='likes_count',
        ),
        migrations.CreateModel(
            name='WallpaperLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallpaper_likes', to=settings.AUTH_USER_MODEL)),
                ('wallpaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='wallpapers.wallpaper')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'wallpaper'), name='unique_user_wallpaper_like')],
            },
        ),
    ]
