# Generated by Django 5.2.10 on 2026-02-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapers', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
